Repository SpiNNakerManchester/IntroLab, pull requests merged in 2021-02, with the labels that each got.

#22 neo_convertor has moved
  synfire/synfire.py
  synfire/synfire_collab.py
Labels: BLOCKER!, enhancement

#21 Turn off automated testing with 2.7
  .github/workflows/python_actions.yml
Labels: enhancement

#23 added 3.9 and rat 3.8
  .github/workflows/python_actions.yml
Labels: enhancement

#24 Move the script testing to the repository that hold the scripts
  .gitignore
  integration_tests/README.md
  integration_tests/__init__.py
  integration_tests/script_builder.py
  integration_tests/test_scripts.py
Labels: enhancement

#25 matplotlib install
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug
